version: "3"

services:

  backend:
    build: ./backend
    image: saloodo-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
    environment:
      - PORT=8000
      - NODE_ENV=development
      - DATABASE_URI=mongodb://mongo_db:27018/saloodo_data

  frontend:
    build: ./frontend
    image: saloodo-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

  mongo_db:
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27017"
